application: graphite-flare-658
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: calendar_parser.application
  
  libraries:
- name: pytz
  version: latest
