application: graphite-flare-658
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  static_dir: HW3.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest