application: graphite-flare-658
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# re-direct to home.html if no path is give
- url: /
  static_files: home.html
  upload: home.html

# access the static resources in the root directory

- url: /(.*)
  static_files: \1
  upload: (.*)

- url: /.*
  static_dir: HW3.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest