application: graphite-flare-658
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /resources
  static_dir: resources
- url: /partials
  static_dir: partials
- url: /.*
  script: dispatcher.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest