application: graphite-flare-658
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  static_dir: HW3.application

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: SearchGoogle.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest